; This file is for the FamiTone2 library and was generated by FamiStudio
; Required flags for Molekin Mine:

.export _music_data_molekin_mine:=music_data_molekin_mine

music_data_molekin_mine:
	.byte 1
	.word @instruments
	.word @samples-3
; 00 : Song 1
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.word 307,256

.export music_data_molekin_mine
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $30 ; 00 : Duty 0
	.word @env0, @env1, @env1
	.byte $00

@env0:
	.byte $cf,$7f,$00,$00
@env1:
	.byte $c0,$7f,$00,$01

@samples:

@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $80
@song0ref5:
	.byte $44, $9d, $00, $9d, $44, $9d, $00, $f9, $a3, $40, $9d, $00, $9d, $40, $9d, $00, $f9, $a3, $3c, $9d, $00, $9d, $3c, $9d
	.byte $00, $f9, $a3, $46, $dd, $00, $f9, $a3, $44, $9d, $00, $9d, $44, $9d, $00, $f9, $a3, $40, $9d, $00, $9d, $40, $9d, $00
	.byte $f9, $a3, $4a, $9d, $00, $9d, $4a, $9d, $00, $f9, $a3, $46, $dd
@song0ref66:
	.byte $00, $f9, $a3, $0a, $9d, $00, $9d, $0a, $9d, $00, $f9, $a3, $1a, $9d, $00, $9d, $1a, $9d, $00, $f9, $a3, $24, $9d, $00
	.byte $9d, $24, $9d, $00, $f9, $a3, $20, $9d, $00, $9d, $20, $9d, $00, $f9, $a3, $14, $9d, $00, $9d, $14, $9d, $00, $f9, $a3
	.byte $0a, $9d, $00, $9d, $0a, $9d, $00, $f9, $a3, $1a, $9d, $00, $9d, $1a, $9d, $00, $f9, $a3, $08, $9d, $00, $9d, $08, $9d
	.byte $ff, $48
	.word @song0ref66
	.byte $00, $f9, $a3, $52, $9d, $00, $9d, $52, $9d, $00, $8d, $54, $8d, $52, $9d, $00, $9d, $52, $9d, $00, $8d, $54, $8d, $58
	.byte $9d, $00, $8d, $5a, $8d, $58, $9d, $00, $8d, $54, $8d, $52, $f9, $83, $00, $f9, $f9, $f9, $f9, $95, $52, $9d, $00, $9d
	.byte $52, $9d, $00, $8d, $4e, $8d, $52, $9d, $00, $9d, $52, $9d, $00, $8d, $54, $8d, $58, $9d, $00, $8d, $5c, $8d, $58, $9d
	.byte $00, $8d, $54, $8d, $52, $f9, $83, $00, $f9, $f9, $f9, $f9, $95
	.byte $ff, $85
	.word @song0ref5
	.byte $ff, $48
	.word @song0ref66
	.byte $00, $f9, $a3, $52, $9d, $00, $9d, $52, $f9, $f9, $f9, $cf, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref249:
	.byte $2c, $9d, $32, $9d, $3a, $9d, $2c, $9d, $32, $9d, $3a, $9d, $2c, $9d, $32, $9d, $28, $9d, $32, $9d, $3a, $9d, $28, $9d
	.byte $32, $9d, $3a, $9d, $28, $9d, $32, $9d, $24, $9d, $32, $9d, $3c, $9d, $24, $9d, $32, $9d, $3c, $9d, $24, $9d, $32, $9d
	.byte $3e, $9d, $3c, $9d, $3e, $bd, $2e, $9d, $3e, $9d, $26, $9d, $2e, $9d
	.byte $ff, $20
	.word @song0ref249
@song0ref314:
	.byte $40, $9d, $3a, $9d, $40, $9d, $28, $9d, $32, $9d, $40, $9d, $22, $9d, $32, $9d, $3e, $9d, $3c, $9d, $3e, $bd, $2e, $9d
	.byte $3e, $9d, $26, $9d, $2e, $9d
	.byte $ff, $30
	.word @song0ref249
@song0ref347:
	.byte $38, $9d, $2e, $9d, $3e, $9d, $26, $9d, $2e, $9d, $3e, $9d, $26, $9d, $2e, $9d, $2c, $9d, $32, $9d, $3a, $9d, $2c, $9d
	.byte $32, $9d, $3a, $9d, $44, $9d, $32, $9d, $40, $9d, $32, $9d, $3a, $9d, $40, $9d, $32, $9d, $3a, $9d, $40, $9d, $32, $9d
	.byte $3a, $bd, $40, $9d, $3a, $9d, $32, $9d, $40, $9d, $3a, $9d, $32, $9d, $38, $9d, $2e, $9d, $3e, $9d, $38, $9d, $2e, $9d
	.byte $3e, $9d, $2e, $9d, $38, $9d, $3a, $9d, $00, $f9, $e3, $4a, $9d, $00, $f9, $e3, $54, $9d, $00, $f9, $e3, $50, $9d, $00
	.byte $f9, $e3, $44, $9d, $00, $f9, $e3, $3a, $9d, $00, $f9, $e3, $4a, $9d, $00, $f9, $e3, $38, $9d, $00, $f9, $e3
	.byte $ff, $3e
	.word @song0ref249
	.byte $ff, $20
	.word @song0ref249
	.byte $ff, $1d
	.word @song0ref314
	.byte $9b, $00
	.byte $ff, $3e
	.word @song0ref249
	.byte $ff, $20
	.word @song0ref249
	.byte $ff, $1e
	.word @song0ref314
	.byte $ff, $30
	.word @song0ref249
	.byte $ff, $76
	.word @song0ref347
	.byte $2c, $9d, $32, $9d, $3a, $f9, $f9, $f9, $cf, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
@song0ref504:
	.byte $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9
	.byte $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $f9, $f9, $f9, $f9, $97, $80
@song0ref545:
	.byte $3a, $9d, $00, $9d, $3a, $9d, $00, $8d, $3c, $8d, $3a, $9d, $00, $9d, $3a, $9d, $00, $8d, $3c, $8d, $40, $9d, $00, $8d
	.byte $42, $8d, $40, $9d, $00, $8d, $3c, $8d, $3a, $f9, $83, $00, $f9, $f9, $f9, $f9, $95, $3a, $9d, $00, $9d, $3a, $9d, $00
	.byte $8d, $36, $8d, $3a, $9d, $00, $9d, $3a, $9d, $00, $8d, $3c, $8d, $40, $9d, $00, $8d, $44, $8d, $40, $9d, $00, $8d, $3c
	.byte $8d, $3a, $f9, $83, $00, $f9, $f9, $f9, $f9, $95
@song0ref627:
	.byte $44, $9d, $00, $9d, $44, $9d, $00, $9d, $44, $9d, $00, $9d, $44, $9d, $00, $9d, $40, $9d, $00, $9d, $40, $9d, $00, $9d
	.byte $40, $9d, $00, $9d, $40, $9d, $00, $9d, $3c, $9d, $00, $9d, $3c, $9d, $00, $9d, $3c, $9d, $00, $9d, $3c, $9d, $00, $9d
	.byte $46, $9d, $00, $9d, $46, $9d, $00, $9d, $46, $9d, $00, $9d, $46, $9d, $00, $9d
	.byte $ff, $20
	.word @song0ref627
	.byte $4a, $9d, $00, $9d, $4a, $9d, $00, $9d, $4a, $9d, $00, $dd, $46, $9d, $00, $9d, $46, $9d, $00, $9d, $46, $9d, $00, $9d
	.byte $46, $9d, $00, $9d
	.byte $ff, $28
	.word @song0ref504
	.byte $ff, $57
	.word @song0ref545
	.byte $f9, $f9, $f9, $cf, $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
	.byte $80
@song0ref737:
	.byte $42, $8d, $5c, $8d, $4a, $8d, $5e, $8d, $00, $8d, $40, $8d, $4e, $8d, $5e, $8d, $00, $8d, $5c, $8d, $42, $8d, $5e, $8d
	.byte $42, $8d, $40, $8d, $4e, $8d, $5e, $8d
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
@song0ref790:
	.byte $42, $8d, $5c
@song0ref793:
	.byte $8d, $00, $8d, $5e, $8d, $42, $8d, $40, $8d, $00, $8d, $5e, $8d, $42, $8d, $5c, $8d, $00, $8d, $5e, $8d, $42, $8d, $40
	.byte $8d, $00, $8d, $5e, $8d, $42, $8d, $5c, $8d, $00, $8d, $5e, $8d, $42, $8d, $40, $8d, $00, $8d, $5e, $8d, $42, $8d, $5a
	.byte $ff, $2f
	.word @song0ref793
	.byte $5c, $8d, $00, $8d, $5e, $8d, $42, $8d, $40, $8d, $00, $8d, $5e, $8d, $42, $8d, $5a
	.byte $ff, $2f
	.word @song0ref793
	.byte $5c, $8d, $00, $8d, $5e, $8d, $42, $8d, $40, $8d, $00, $8d, $5e, $8d, $42, $8d, $5a
	.byte $ff, $2f
	.word @song0ref793
@song0ref884:
	.byte $5c, $8d, $00, $8d, $5e, $8d, $42, $8d, $40, $8d, $00, $8d, $5e, $8d, $42, $8d, $5a, $8d, $00, $8d, $5e, $8d, $42, $8d
	.byte $40, $8d, $00, $8d, $5e, $8d
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $33
	.word @song0ref790
	.byte $ff, $2f
	.word @song0ref793
	.byte $ff, $1e
	.word @song0ref884
	.byte $ff, $33
	.word @song0ref790
	.byte $ff, $2f
	.word @song0ref793
	.byte $ff, $1e
	.word @song0ref884
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $33
	.word @song0ref790
	.byte $ff, $2f
	.word @song0ref793
	.byte $ff, $1e
	.word @song0ref884
	.byte $ff, $33
	.word @song0ref790
	.byte $ff, $2f
	.word @song0ref793
	.byte $ff, $1e
	.word @song0ref884
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $ff, $20
	.word @song0ref737
	.byte $42, $8d, $5c, $8d, $00, $8d, $5e, $8d, $42, $8d, $40, $f9, $f9, $f9, $bf, $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
	.byte $ff, $28
	.word @song0ref504
	.byte $ff, $28
	.word @song0ref504
	.byte $ff, $28
	.word @song0ref504
	.byte $ff, $19
	.word @song0ref504
	.byte $fd
	.word @song0ch4loop
